### ISSUE TITLE
Is the C compiler a serious effort?

### ISSUE THREAD

**Issue by ghost** [rochus-keller/EiGen#3]
Will you make it a standard compliant and optimizing C compiler?

**Comment by rochus-keller** [comment]
There is no optimizer yet for the Eigen Compiler Suite. I assume that Florian will implement one some day. The primary goal at the moment is to have a decently good C compiler for the Eigen suite which can eat most of the relevant C code. I first tried Chibicc, which is too limited. Cparser supports all of C99 and even some GNU extensions, but I don't think I will adapt everything. My actual goal is to implement my Micron language; but since Eigen is a world by it's own, this only makes sense if there is also a C compiler.

**Comment by rochus-keller** [comment]
If you're interested in performance data, see https://github.com/rochus-keller/Oberon/blob/master/testcases/Are-we-fast-yet/Are-we-fast-yet_results.ods. 

I actually implemented two C compiler backends so far, one for Chibicc and one for Cparser. Chibicc generates pretty slow executables (about factor 3.5 slower than GCC -O0). Cparser output currently is 1.5 times slower than GCC -O0, but the code generator can still be improved.
